#!/usr/bin/env python3
"""Generate bit-exact Q7 data for the scaled radix-2 int8 FFT testbench."""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

try:
    from .fft_groundtruth import make_input
except ImportError:
    from fft_groundtruth import make_input


def rnu_shift(value: int, shift: int) -> int:
    return (value + (1 << (shift - 1))) >> shift


def sat_i8(value: int) -> int:
    return max(-128, min(127, value))


def quantize_q7(value: float) -> int:
    return sat_i8(int(np.floor(value * 128.0 + 0.5)))


def reverse_bits(value: int, bits: int) -> int:
    result = 0
    for _ in range(bits):
        result = (result << 1) | (value & 1)
        value >>= 1
    return result


def scaled_fft_q7(real: np.ndarray, imag: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    size = real.size
    stages = size.bit_length() - 1
    out_r = [int(real[reverse_bits(i, stages)]) for i in range(size)]
    out_i = [int(imag[reverse_bits(i, stages)]) for i in range(size)]

    block_size = 2
    while block_size <= size:
        half = block_size // 2
        for offset in range(half):
            if offset == 0:
                wr, wi = 127, 0
            else:
                angle = -2.0 * np.pi * offset / block_size
                wr = quantize_q7(float(np.cos(angle)))
                wi = quantize_q7(float(np.sin(angle)))
            for block in range(0, size, block_size):
                even = block + offset
                odd = even + half
                er, ei = out_r[even], out_i[even]
                or_, oi = out_r[odd], out_i[odd]
                if offset == 0:
                    tr, ti = or_, oi
                else:
                    tr = sat_i8(rnu_shift(or_ * wr - oi * wi, 7))
                    ti = sat_i8(rnu_shift(oi * wr + or_ * wi, 7))
                out_r[even] = rnu_shift(er + tr, 1)
                out_i[even] = rnu_shift(ei + ti, 1)
                out_r[odd] = rnu_shift(er - tr, 1)
                out_i[odd] = rnu_shift(ei - ti, 1)
        block_size *= 2
    return np.asarray(out_r, dtype=np.int8), np.asarray(out_i, dtype=np.int8)


def format_array(name: str, values: np.ndarray) -> list[str]:
    lines = [f"static const int8_t {name}[FFT_INT8_SIZE] __attribute__((aligned(64))) = {{"]
    for offset in range(0, values.size, 16):
        chunk = values[offset : offset + 16]
        lines.append("    " + ", ".join(str(int(v)) for v in chunk) + ",")
    lines.append("};")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--size", type=int, default=1024)
    parser.add_argument("--header", type=Path, required=True)
    args = parser.parse_args()
    if args.size < 2 or args.size & (args.size - 1):
        raise ValueError("--size must be a power of two and at least 2")

    signal = make_input(args.size)
    input_r = np.asarray([quantize_q7(float(v)) for v in signal.real], dtype=np.int8)
    input_i = np.asarray([quantize_q7(float(v)) for v in signal.imag], dtype=np.int8)
    output_r, output_i = scaled_fft_q7(input_r, input_i)
    lines = [
        "/* Generated by py/fft/fft_int8_groundtruth.py. Do not edit manually. */",
        "#ifndef FFT_INT8_VECTORS_H",
        "#define FFT_INT8_VECTORS_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define FFT_INT8_SIZE {args.size}",
        "",
    ]
    for name, values in (
        ("fft_int8_input_real", input_r),
        ("fft_int8_input_imag", input_i),
        ("fft_int8_groundtruth_real", output_r),
        ("fft_int8_groundtruth_imag", output_i),
    ):
        lines.extend(format_array(name, values))
        lines.append("")
    lines.extend(("#endif /* FFT_INT8_VECTORS_H */", ""))
    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text("\n".join(lines), encoding="ascii")
    print(f"FFT size: {args.size}")
    print(f"total scale: 1/{args.size}")
    print(f"saved: {args.header}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
