#!/usr/bin/env python3
# SPDX-FileContributor: Person: Stanley Lee
# SPDX-License-Identifier: Apache-2.0
"""Generate and validate a deterministic complex FFT ground truth."""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import numpy as np


def make_input(size: int) -> np.ndarray:
    """Create the deterministic signal shared with testbench/fft/fft.c."""
    if size == 16:
        real = np.array(
            [
                0.5, -1.0, 0.25, 2.0, -0.75, 0.125, 1.5, -0.5,
                0.875, -1.25, 0.625, 0.0, -0.375, 1.125, -0.875, 0.75,
            ],
            dtype=np.float32,
        )
        imag = np.array(
            [
                0.0, 0.5, -0.25, 0.75, -1.0, 0.375, 0.0, -0.625,
                0.25, -0.125, 1.0, -0.5, 0.625, -0.75, 0.125, 0.875,
            ],
            dtype=np.float32,
        )
        return (real + 1j * imag).astype(np.complex64)

    rng = np.random.default_rng(seed=0)
    real = rng.uniform(-1.0, 1.0, size=size).astype(np.float32)
    imag = rng.uniform(-1.0, 1.0, size=size).astype(np.float32)
    return (real + 1j * imag).astype(np.complex64)


def direct_dft(signal: np.ndarray) -> np.ndarray:
    """Compute the DFT definition directly."""
    size = signal.size
    sample = np.arange(size, dtype=np.float64)
    bin_index = sample.reshape(-1, 1)
    twiddle = np.exp(-2j * np.pi * bin_index * sample / size)
    return twiddle @ signal.astype(np.complex128)


def write_complex_csv(path: Path, values: np.ndarray) -> None:
    with path.open("w", newline="", encoding="ascii") as output_file:
        writer = csv.writer(output_file)
        writer.writerow(("index", "real", "imag"))
        for index, value in enumerate(values):
            writer.writerow((index, f"{value.real:.9g}", f"{value.imag:.9g}"))


def print_float_array(name: str, values: np.ndarray) -> None:
    """Print one component in a format that can be copied into the C testbench."""
    print(f"static const float {name}[{values.size}] = {{")
    for offset in range(0, values.size, 4):
        chunk = values[offset : offset + 4]
        print("    " + ", ".join(f"{float(value):.9f}f" for value in chunk) + ",")
    print("};")


def format_c_array(name: str, values: np.ndarray) -> list[str]:
    lines = [
        f"static const float {name}[FFT_SIZE] __attribute__((aligned(64))) = {{"
    ]
    for offset in range(0, values.size, 4):
        chunk = values[offset : offset + 4]
        values_text = ", ".join(f"{float(value):.9f}f" for value in chunk)
        lines.append(f"    {values_text},")
    lines.append("};")
    return lines


def write_c_header(path: Path, signal: np.ndarray, groundtruth: np.ndarray) -> None:
    """Write the complete input and NumPy ground truth consumed by fft.c."""
    lines = [
        "/* Generated by py/fft/fft_groundtruth.py. Do not edit manually. */",
        "#ifndef FFT_VECTORS_H",
        "#define FFT_VECTORS_H",
        "",
        f"#define FFT_SIZE {signal.size}",
        "",
    ]
    arrays = (
        ("input_real", signal.real),
        ("input_imag", signal.imag),
        ("groundtruth_real", groundtruth.real),
        ("groundtruth_imag", groundtruth.imag),
    )
    for name, values in arrays:
        lines.extend(format_c_array(name, values))
        lines.append("")
    lines.extend(("#endif /* FFT_VECTORS_H */", ""))
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate NumPy FFT ground truth and verify it with a direct DFT."
    )
    parser.add_argument("--size", type=int, default=16, help="FFT size (default: 16).")
    parser.add_argument(
        "--output-dir", type=Path, help="Optional directory for input/output CSV files."
    )
    parser.add_argument(
        "--header",
        type=Path,
        help="Write a C header containing FFT_SIZE, input, and ground truth arrays.",
    )
    parser.add_argument(
        "--atol", type=float, default=1e-5, help="Absolute tolerance (default: 1e-5)."
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.size <= 0 or args.size & (args.size - 1):
        raise ValueError("--size must be a positive power of two")
    if args.atol < 0:
        raise ValueError("--atol must be non-negative")

    signal = make_input(args.size)
    groundtruth = np.fft.fft(signal).astype(np.complex64)
    reference = direct_dft(signal)
    max_error = float(np.max(np.abs(groundtruth.astype(np.complex128) - reference)))

    print("FFT input:")
    print_float_array("input_real", signal.real)
    print_float_array("input_imag", signal.imag)

    print("\nFFT ground truth from numpy.fft.fft:")
    print_float_array("groundtruth_real", groundtruth.real)
    print_float_array("groundtruth_imag", groundtruth.imag)

    print("\nGround truth by frequency bin:")
    print("bin        real             imag")
    for index, value in enumerate(groundtruth):
        print(f"{index:3d}  {value.real:15.9f}  {value.imag:15.9f}")
    print(f"\nmax |numpy.fft.fft - direct DFT|: {max_error:.3e}")

    if args.output_dir is not None:
        args.output_dir.mkdir(parents=True, exist_ok=True)
        input_path = args.output_dir / "fft_input.csv"
        output_path = args.output_dir / "fft_groundtruth.csv"
        write_complex_csv(input_path, signal)
        write_complex_csv(output_path, groundtruth)
        print(f"saved: {input_path}")
        print(f"saved: {output_path}")

    if args.header is not None:
        write_c_header(args.header, signal, groundtruth)
        print(f"saved: {args.header}")

    if max_error > args.atol:
        print(f"FAIL: error exceeds tolerance {args.atol:.3e}")
        return 1
    print(f"PASS: error is within tolerance {args.atol:.3e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
