# Copyright 2026 Stanley Lee
# SPDX-License-Identifier: Apache-2.0

function(nn_linux_profile profile out_arch out_tune)
  if(profile STREQUAL "default")
    set(arch rv64gc)
    set(tune rocket)
  elseif(profile STREQUAL "zvl64b")
    set(arch rv64gcv_zvbb_zvl64b_zve64d)
    set(tune "")
  elseif(profile STREQUAL "zvl128b")
    set(arch rv64gcv_zvbb_zvl128b_zve64d)
    set(tune rocket)
  elseif(profile STREQUAL "zvl256b")
    set(arch rv64gcv_zvbb_zvl256b_zve64d)
    set(tune rocket)
  elseif(profile STREQUAL "zvl512b")
    set(arch rv64gcv_zvbb_zvl512b_zve64d)
    set(tune rocket)
  elseif(profile STREQUAL "zvl512b_cycle")
    set(arch rv64gcv_zicntr_zihpm_zvbb_zvl512b_zve64d)
    set(tune rocket)
  elseif(profile STREQUAL "RVV")
    set(arch rv64imafdcbvzicsr_zifencei_zihpm_zvl256b_zve64d_zvfh_zfh_zba_zbb_zbs_zvbb)
    set(tune rocket)
  elseif(profile STREQUAL "MINV64D64RocketGENESYS2Config")
    set(arch rv64imafdcbzicsr_zifencei_zihpm_zvl64b_zve64d_zvfh_zfh_zba_zbb_zbs_zvbb)
    set(tune rocket)
  elseif(profile STREQUAL "DSPV128D128RocketGENESYS2Config")
    set(arch rv64imafdcbvzicsr_zifencei_zihpm_zvl128b_zve64d_zvfh_zfh_zba_zbb_zbs_zvbb)
    set(tune rocket)
  else()
    message(FATAL_ERROR "Unknown NN_CONFIG='${profile}'")
  endif()
  set(${out_arch} "${arch}" PARENT_SCOPE)
  set(${out_tune} "${tune}" PARENT_SCOPE)
endfunction()

function(nn_baremetal_profile profile out_arch)
  if(profile STREQUAL "V128D128B")
    set(arch rv64gcv_zvl128b_zve64d_zvfh_zfh_zba_zbb_zbs_zvbb)
  elseif(profile STREQUAL "V256D128B")
    set(arch rv64gcv_zvl256b_zve64d_zvfh_zfh_zba_zbb_zbs_zvbb)
  elseif(profile STREQUAL "V512D128B")
    set(arch rv64gcv_zvl512b_zve64d_zvfh_zfh_zba_zbb_zbs_zvbb)
  else()
    message(FATAL_ERROR "Unknown NN_HARDWARE_CONFIG='${profile}'")
  endif()
  set(${out_arch} "${arch}" PARENT_SCOPE)
endfunction()
